project_id = "elrfdqlkitczdhfyrlui"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.request-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.request-payment-otp]
verify_jwt = false

[functions.verify-payment-otp]
verify_jwt = false

[functions.submit-crypto-payment]
verify_jwt = false

[functions.confirm-bank-payment]
verify_jwt = false
