export const MEDIA = {
  logoWhite: '/images/logo-white.png',
  heroHostKit: '/images/product-host-kit.png',
  heroGuestGuide: '/images/hero-guest-guide.png',
  heroFinance: '/images/hero-finance.png',
  productHostKit: '/images/product-host-kit.png',
  productGuestGuide: '/images/product-guest-guide.png',
  productFinance: '/images/product-finance.png',
  liveDemoQrEn: '/images/live-demo-qr-en.jpg?v=2',
  liveDemoQrTr: '/images/live-demo-qr-tr.jpg?v=2',
  excelExport: '/images/exel.png',
  platformWindows: '/images/icons/windows.png',
  platformMacos: '/images/icons/macos.png',
  platformLinux: '/images/icons/linux.png',
} as const;
